# ── IBM MQ connection parameters ────────────────────────────────────────────
# Uncomment ccdt-url to use CCDT instead of connection-list (mutually exclusive)
# file:../ccdt/ccdt.nativeha.json  for Native HA — use with queue-manager QM1
# file:../ccdt/ccdt.cluster.json   for Native HA + Cluster — use with queue-manager *UNIQA
#ibm.mq.ccdt-url=file:../ccdt/ccdt.cluster.json
ibm.mq.connection-list=localhost(1414),localhost(1415),localhost(1416)
ibm.mq.application-name=all-in-one
ibm.mq.channel=DEV.APP.SVRCONN
#ibm.mq.queue-manager=*UNIQA
ibm.mq.queue-manager=QM1
ibm.mq.username=app
ibm.mq.password=passw0rd
ibm.mq.queue=DEV.DEMO.QL.IN
ibm.mq.client-reconnect-timeout=5


# Logging
# Set a specific package to DEBUG
quarkus.log.category."com.example.resource.InfoResource".level=DEBUG

mp.messaging.outgoing.mq-put.connector=smallrye-jms
mp.messaging.outgoing.mq-put.destination=${ibm.mq.queue}
mp.messaging.outgoing.mq-put.destination-type=queue

# ── Micrometer / Prometheus
quarkus.micrometer.export.prometheus.enabled=true

# ── OpenTelemetry
quarkus.otel.enabled=false
quarkus.otel.metrics.enabled=false
# quarkus.otel.sdk.disabled => True, disable at runtime
quarkus.otel.sdk.disabled=true
quarkus.application.name=all-in-one
quarkus.otel.exporter.otlp.endpoint=http://localhost:4317 
#quarkus.otel.exporter.otlp.headers=authorization=Bearer my_secret 
#quarkus.log.console.format=%d{HH:mm:ss} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n  
 

# ── Quarkus HTTP port 
quarkus.http.port=8080
