# ── IBM MQ connection parameters ────────────────────────────────────────────
# Uncomment ccdt-url to use CCDT instead of connection-list (mutually exclusive)
# file:../ccdt/ccdt.nativeha.json  for Native HA — use with queue-manager QM1
# file:../ccdt/ccdt.cluster.json   for Native HA + Cluster — use with queue-manager *UNIQA
#ibm.mq.ccdt-url=file:../ccdt/ccdt.cluster.json
ibm.mq.connection-list=host.containers.internal(1414),host.containers.internal(1415),host.containers.internal(1416)
ibm.mq.application-name=all-in-one
ibm.mq.channel=DEV.APP.SVRCONN
#ibm.mq.queue-manager=*UNIQA
ibm.mq.queue-manager=QM1
ibm.mq.username=app
ibm.mq.password=passw0rd
ibm.mq.queue=DEV.DEMO.QL.IN
ibm.mq.client-reconnect-timeout=5

# Logging
# Set a specific package to DEBUG
quarkus.log.category."com.example.resource.InfoResource".level=INFO

mp.messaging.outgoing.mq-put.connector=smallrye-jms
mp.messaging.outgoing.mq-put.destination=${ibm.mq.queue}
mp.messaging.outgoing.mq-put.destination-type=queue

# ── Micrometer / Prometheus
quarkus.micrometer.export.prometheus.enabled=true

# ── Quarkus HTTP port 
quarkus.http.port=8080
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=/.*/
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=Content-Type,Accept,Authorization